<div class="produits">
    <h1>Nos produits </h1> 
    <article class="choix"> 
            <a href="/projet/product/">
                <div class="categories">
                    <img src="/projet/public/img/logo.png" class="card-img-top" style="height: 8rem;" alt="logo YHTechnologies">
         <h5>Tous les produits</h5>  
                </div>
            </a>   
    </article> 
    <h2>Nos produits dans nos boutiques</h2>
    <article class="choix">
    <?php foreach ($params['products'] as $product):?>
      <?php if ($product->category_id==$params['category']->id):?>
            <div class="produit">
                <img class="image" src="<?= $product->picture ?>" alt="<?= $product->permalink ?>"> 
                <div class="middle"> 
                    <div class="text">
                        <a href="/projet/product/show/<?= $product->id ?>">Voir </a>
                        <a href="#" >Commander</a>
                    </div>
                </div>
                <h4><?= $product->name ?></h4>
                <p>Prix : <?= $product->price ?> Euro</p>
                <p>Reference : <?= $product->reference ?></p>  
            </div>
      <?php endif ?>
    <?php endforeach ?>
  </div> 
</div>
