<h1><?= $params['user']->firstname ?? 'Créer un nouveau user'?></h1> 
    <div class="text-right">
        <a href="javascript:history.go(-1)" class="btn btn-outline-primary"><i class="fa fa-backward"></i> Retour</a>
    </div>
<form action="<?= isset ($params['user']) ? "/projet/admin/users/edit/{$params['user']->id}":
  "/projet/admin/users/create" ?>" method="POST"> 
    <fieldset>
      <?php if (!empty($_SESSION['errors'])): ?> 
        <?php foreach($_SESSION['errors'] as $errorsArray): ?>
          <?php foreach($errorsArray as $errors): ?>
              <div class="alert alert-danger">
                  <?php foreach($errors as $error): ?>
                      <?= $error ?>
                  <?php endforeach ?>
              </div>
          <?php endforeach ?>
      <?php endforeach ?>
    <?php elseif (!empty($_SESSION['errorsUpdate'])): ?> 
      <?php foreach($_SESSION['errorsUpdate'] as $errorsArray): ?>
          <?php foreach($errorsArray as $errors): ?>
              <div class="alert alert-danger">
                  <?php foreach($errors as $error): ?>
                      <?= $error ?>
                  <?php endforeach ?>
              </div>
          <?php endforeach ?>
      <?php endforeach ?>  
    <?php endif ?>
        <div class="form-group">
          <label for="firstname">Firstname </label>
          <input type="text" class="form-control" id="firstname" name="firstname" value="<?= $params['user']->firstname ?? ''?>">
        </div>
        <div class="form-group">
          <label for="lastname">Lastname </label>
          <input type="text" class="form-control" id="lastname" name="lastname" value="<?= $params['user']->lastname ?? ''?>">
        </div>
        <div class="form-group">
          <label for="email">Email </label>
          <input type="text" class="form-control" id="email" name="email" value="<?= $params['user']->email ?? ''?>">
        </div>
        <div class="form-group">
          <label for="password">Password </label>
          <input type="password" class="form-control" id="password" name="password" value="<?= $params['user']->password ?? ''?>">
        </div>
        <div class="form-group">
          <label for="phone">Phone </label>
          <input type="text" class="form-control" id="phone" name="phone" value="<?= $params['user']->phone ?? ''?>">
        </div>
        <div class="form-group">
          <label for="picture">Picture </label>
          <input type="picture" class="form-control" id="picture" name="picture" value="<?= $params['user']->picture ?? ''?>">
        </div>
        <div class="form-group">
          <label for="shippingAdressLine">Adresse</label>
          <input type="shippingAdressLine" class="form-control" id="shippingAdressLine" name="shippingAdressLine" value="<?= $params['user']->shippingAdressLine ?? ''?>">
        </div>        
        <div class="form-group">
          <label for="shippingZipCode">Code Postal</label>
          <input type="shippingZipCode" class="form-control" id="shippingZipCode" name="shippingZipCode" value="<?= $params['user']->shippingZipCode ?? ''?>">
        </div>
        <div class="form-group">
            <label for="role"class="form-group">Compte</label>
            <select id="role" name="role" class="custom-select">
                <option value=0 selected>Valide</option>
                <option value=2>Ban</option>
            </select>
            <div></div>
        </div> 
        
        <button type="submit" class="btn btn-primary">
          <?= isset($params['user']) ?'Modifier le client':'Enregister le client'?></button>
    </fieldset>
</form>