 <?php if (($_SESSION['success'])==true): ?> 
  <div class='alert alert-success h5'>Categorie enregistré</div> 
<?=$_SESSION['success']=false ?>
<?php endif; ?>
 <?php if (($_SESSION['delete'])==true): ?> 
  <div class='alert alert-danger h5'>Categorie effacé</div>
  <?= $_SESSION['delete']=false?>
<?php endif; ?>
<h1 class="text-center mb-5">Les Categorie</h1>  
  <p>
    <div class="text-right"><a href="javascript:history.go(-1)" class="btn btn-outline-primary"><i class="fa fa-backward"></i> Retour</a>
  </div>
  <div class="text-left"><a href="/projet/admin/category/create" class="btn btn-outline-primary "><i class="fa fa-plus"></i> Ajouter une categorie </a>
</div>
</p>
<table class="table"> 
  <thead class="table-dark"> 
    <tr class="text-center"> 
      <th scope="col">#</th>
      <th scope="col">Image</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Creation</th> 
      <th scope="col">Action</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($params['category'] as $category):?>
    <tr class="text-center"> 
      <th scope="row"><?= $category->id?></td> 
      <td><img src="<?= $category->picture ?>"style="width:50px;height=50px"></td>
      <td> <?= $category->title ?></td>  
      <td> <?= $category->description ?></td>  
      <td>Creer le <?= $category->getCreatedAt() ?></td>  
      <td>
        <a href="/projet/admin/category/show/<?= $category->id ?>"class="btn btn-primary"><i class="fa fa-eye"></i> Voir </a>
        <a href="/projet/admin/category/edit/<?= $category->id ?>"class="btn btn-warning"><i class="fa fa-edit"></i> Modifier</a>  
        <form action="/projet/admin/category/destroy/<?= $category->id ?>" method="POST" class="d-inline">
            <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Supprimer </button>
        </form> 
      </td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>



