<div class="home">
    <?php if ((isset($_SESSION['success']))&&(($_SESSION['success'])==true)): ?> 
        <h1>Vous ete conneter</h1> 
        <?= $_SESSION['success']=false ?>
    <?php endif; ?> 
<h1>Bienvenue cher client</h1> 

    <div class="page-wrapper"> 
        <div class="post-slider"> 
            <i class="fa fa-arrow-circle-left prev"></i> 
            <i class="fa fa-arrow-circle-right next"></i> 
            <div id ="post-wrapper"class="post-wrapper">
                <div class="post">
                    <img src="/projet/public/img/wallpaper1.jpeg" class="slider-img">1           
                </div> 
                <div class="post">
                    <img src="/projet/public/img/wallpaper2.jpeg" class="slider-img">2 
                </div>    
                <div class="post">
                    <img src="/projet/public/img/wallpaper3.jpeg" class="slider-img">3 
                </div> 
                <div class="post">
                    <img src="/projet/public/img/wallpaper2.jpeg" class="slider-img">4 
                </div>  
            </div>
        </div>
    </div> 
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis..Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, reiciendis..
</p> 
</div>

	