<div>
    <h1>Produits N° <?= $params['product']->id ?></h1>   
    <div class="text-right">
        <a href="javascript:history.go(-1)" class="btn btn-outline-primary"><i class="fa fa-backward"></i> Retour</a>
    </div>
  <div class="ml-5">
  <h2>Nom : <?= $params['product']->name ?></h2>
  <h3>Catégory : <?= $params['category']->title ?></h3> 
  </div>
  <article class="show ml-5 mt-4"> 
      <img src="<?= $params['product']->picture ?>"style="width:300px;height=300px" alt="<?= $params['product']->permalink ?>">
      <div class="ml-5">
      <h4>Reference : <?= $params['product']->reference ?> </h4>
      <h4>Creer le <?= $params['product']->getCreatedAt()?> : </h4>
      <p><?= $params['product']->description?></p>
      <h4>Quantité en stock : <?= $params['product']->quantity?></h4>
      <h4>Prix de l'unité : <?= $params['product']->price?></h4>
      </div>
            </article>
            <div class="text-right">
        <a href="/projet/admin/product/edit/<?= $params['product']->id ?>"class="btn btn-warning">Modifier</a>  
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="fa fa-trash"></i> Supprimer </button>
    </div>
</div>  
<div class="modal fade" id="exampleModal" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Etes vous sur ?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
      </div> 
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <form action="/projet/admin/product/destroy/<?= $params['product']->id ?>" method="POST" class="d-inline">
          <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Valider </button>
        </form>
      </div>
    </div>
  </div>
</div>


